--
--
-- Seção 13 - Tratamento de Exceções
--
-- Aula 1 - Tratamento de Exceções
--
-- Aula 080

-- Tratamento de Exceções Pré-definidas Oracle
/*
- SÃO AS EXCEÇÕES EM QUE AO OCORRER JÁ EXISTE UM TRATAMENTO DE UMA MENSAGEM PRÉ-DEFINIDA
  DO BD ORACLE.
- HÁ AS EXCEÇÕES DEFINIDAS PELO DESENVOLVEDOR. QUE UTILIZAM O PRAGMA EXCEPTION_INIT
- EXCEÇÕES NÃO TRATADAS SE PROPAGAM PARA O AMBIENTE CHAMADOR, EXEMPLO UM BLOCO SUPERIOR
  QUE TENHA CHAMADO AQUELE BLOCO PL/SQL INFERIOR. CASO NÃO HAJA MAIS BLOCOS HIERARQUICOS
  PARA SE PROPAGAR RETORNA A EXCEÇÃO PARA O USUÁRIO OU PARA O PROGRAMA QUE O CHAMOU.
  EXCEÇÃO TRATADA NÃO É UM ERRO. CASO NÃO SEJA TRATADA SE TORNA UM ERRO.
  EXEMPLO DE EXCEÇOES PRÉ-DEFINIDAS:
  COLLECTION_IS_NULL    ORA-06531 - TENTATIVA DE APLICAR UM MÉTODO QUE NÃO EXISTE
  CURSOR_ALREADY_OPEN   ORA-06511 - TENTATIVA DE ABRIR UM CURSOR JÁ ABERTO
  DUP_VAL_ON_INDEX      ORA-00001 - TENTATIVA DE INSERIR UM VALOR DUPLICADO EM UM INDICE ÚNICO
  INVALID_CURSOR        ORA-01001 - OPERAÇÃO ILEGAL EM UM CURSOR.
  INVALID_NUMBER        ORA-01722 - FALHA NA CONVERSÃO
  LOGIN_DENIED          ORA-01017 - USUÁRIO OU SENHA INVÁLIDO
  NO_DATA_FOUND         ORA-01403 - SELECT NÃO RETORNA NENHUMA LINHA
  NOT_LOGGED_ON         ORA-01012 - PL/SQL EXECUTADA COM BANCO NÃO LOGADO
  TIMEOUT_ON_RESOURCE
  TOO_MANY_ROWS
  VALUE_ERROR
  ZERO_DIVIDE
  
  SQLCODE - RETRORNA O CÓDIGO DO ERRO.
  SQLERRM - RETORNA A MENSAGEM DO ERRO.
  
*/
SET SERVEROUTPUT ON
SET VERIFY OFF
ACCEPT  pEmployee_id PROMPT 'Digite o Id do Empregado: '
DECLARE
  vFirst_name   employees.first_name%TYPE;
  vLast_name    employees.last_name%TYPE;
  vEmployee_id  employees.employee_id%TYPE := &pEmployee_id;
BEGIN
  SELECT first_name, last_name
  INTO   vfirst_name, vlast_name
  FROM   employees
  WHERE  employee_id = vEmployee_id;
  DBMS_OUTPUT.PUT_LINE('Empregado: ' || vfirst_name || ' ' || vlast_name);
EXCEPTION
  WHEN NO_DATA_FOUND 
  THEN
     RAISE_APPLICATION_ERROR(-20001, 'Empregado não encontrado, id = ' || 
     TO_CHAR(vEmployee_id));
  WHEN OTHERS 
  THEN
     RAISE_APPLICATION_ERROR(-20002, 'Erro Oracle - ' || SQLCODE || SQLERRM);
END;


